export const INITIAL_CAMERA = Object.freeze({ x: 28, y: 92, scale: 1 });

export const DEMO_NODES = Object.freeze([
  {
    id: "video-landscape",
    kind: "media",
    mediaType: "video",
    title: "城市氛围参考",
    src: "assets/city-landscape.webp",
    sourceWidth: 1920,
    sourceHeight: 1080,
    x: 0,
    y: 0,
  },
  {
    id: "image-portrait",
    kind: "media",
    mediaType: "image",
    title: "角色造型参考",
    src: "assets/portrait.webp",
    sourceWidth: 1080,
    sourceHeight: 1920,
    x: 0,
    y: 520,
  },
  {
    id: "image-square",
    kind: "media",
    mediaType: "image",
    title: "色彩与材质",
    src: "assets/material-square.webp",
    sourceWidth: 2048,
    sourceHeight: 2048,
    x: 390,
    y: 520,
  },
  {
    id: "image-panorama",
    kind: "media",
    mediaType: "image",
    title: "环境全景参考",
    src: "assets/city-panorama.webp",
    sourceWidth: 4096,
    sourceHeight: 1024,
    x: 0,
    y: 920,
  },
  {
    id: "text-brief",
    kind: "text",
    title: "镜头意图",
    body: "傍晚的城市街口，镜头保持平视。角色从画面左侧进入，在霓虹反射最亮的位置短暂停留。画面需要保留真实街景的层次，同时让角色轮廓清晰可辨。",
    width: 320,
    height: 248,
    x: 680,
    y: 0,
  },
  {
    id: "process-generate",
    kind: "process",
    title: "生成画面",
    subtitle: "参考素材 + 镜头意图",
    width: 280,
    height: 180,
    x: 680,
    y: 300,
  },
]);
